// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/create-account.ts";
import * as $1 from "./routes/get-comments.ts";
import * as $2 from "./routes/list-comments.ts";
import * as $3 from "./routes/list-sites.ts";
import * as $4 from "./routes/list-users.ts";
import * as $5 from "./routes/login.ts";
import * as $6 from "./routes/send-comment.ts";

const manifest = {
  routes: {
    "./routes/create-account.ts": $0,
    "./routes/get-comments.ts": $1,
    "./routes/list-comments.ts": $2,
    "./routes/list-sites.ts": $3,
    "./routes/list-users.ts": $4,
    "./routes/login.ts": $5,
    "./routes/send-comment.ts": $6,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
