// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/Affiliate.tsx";
import * as $1 from "./routes/Login.tsx";
import * as $2 from "./routes/SignUp.tsx";
import * as $3 from "./routes/[name].tsx";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Affilate.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/LoginForm.tsx";
import * as $$3 from "./islands/SignupForm.tsx";

const manifest = {
  routes: {
    "./routes/Affiliate.tsx": $0,
    "./routes/Login.tsx": $1,
    "./routes/SignUp.tsx": $2,
    "./routes/[name].tsx": $3,
    "./routes/api/joke.ts": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Affilate.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/LoginForm.tsx": $$2,
    "./islands/SignupForm.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
